apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: "{{ .DexServer.Name }}"
  name: "{{ .DexServer.Name }}"
  namespace: "{{ .DexServer.Namespace }}"
data:
  config.yaml: |
{{ .ConfigYaml | indent 4 }}

