# Copyright Red Hat

apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: "{{ .ServingCertSecretName }}"
  labels:
    app: "{{ .DexServer.Name }}"
  name: "{{ .DexServer.Name }}"
  namespace: "{{ .DexServer.Namespace }}"
spec:
  ports:
  - name: http
    port: 5556
    protocol: TCP
    targetPort: 5556
  selector:
    app: "{{ .DexServer.Name }}"
  type: ClusterIP
