# permissions for end users to view dexclients.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dexclient-viewer-role
rules:
- apiGroups:
  - auth.identitatem.io
  resources:
  - dexclients
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - auth.identitatem.io
  resources:
  - dexclients/status
  verbs:
  - get
