# permissions for end users to edit dexservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dexserver-editor-role
rules:
- apiGroups:
  - auth.identitatem.io
  resources:
  - dexservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - auth.identitatem.io
  resources:
  - dexservers/status
  verbs:
  - get
