# permissions for end users to view dexservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dexserver-viewer-role
rules:
- apiGroups:
  - auth.identitatem.io
  resources:
  - dexservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - auth.identitatem.io
  resources:
  - dexservers/status
  verbs:
  - get
