
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - auth.identitatem.io
  resources:
  - dexclients
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - auth.identitatem.io
  resources:
  - dexclients/finalizers
  verbs:
  - update
- apiGroups:
  - auth.identitatem.io
  resources:
  - dexclients/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - auth.identitatem.io
  resources:
  - dexservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - auth.identitatem.io
  resources:
  - dexservers/finalizers
  verbs:
  - update
- apiGroups:
  - auth.identitatem.io
  resources:
  - dexservers/status
  verbs:
  - get
  - patch
  - update
