apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: dex-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: DexClient is the Schema for the dexclients API
      displayName: Dex Client
      kind: DexClient
      name: dexclients.auth.identitatem.io
      version: v1alpha1
    - description: DexServer is the Schema for the dexservers API
      displayName: Dex Server
      kind: DexServer
      name: dexservers.auth.identitatem.io
      version: v1alpha1
  description: dex operator
  displayName: dex-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - dex
  - operator
  links:
  - name: Dex Operator
    url: https://dex-operator.domain
  maintainers:
  - email: cdoan@redhat.com
    name: cdoan
  maturity: alpha
  provider:
    name: redhat.com
    url: redhat.com
  version: 0.0.0
