apiVersion: auth.identitatem.io/v1alpha1
kind: DexServer
metadata:
  name: dexserver-sample
spec:
  issuer: https://dexserver-sample.apps.pool-sno-8x32-n9kps.demo.red-chesterfield.com/dex
  enablePasswordDB: false
  storage:
    type: kubernetes
    config:
      inCluster: true
  web:
    http: 0.0.0.0:5556
    tlsCert: secretRef
    tlsKey: secretRef
  grpc:
    addr: 0.0.0.0:5557
    tlsCert: secretRef
    tlsKey: secretRef
    tlsClientCA: secretRef
  expiry:
    deviceRequests: "5m"
    signingKeys: "6h"
    idTokens: "24h"
    refreshTokens:
      reuseInterval: "3s"
      validIfNotUsedFor: "2160h"
      absoluteLifetime: "3960h"
  logger:
    level: "1"
    format: "json"
  oauth2:
    responseTypes:
    - "code"
    - "token"
    skipApprovalScreen: false
    alwasyShowLoginScreen: false
    passwordConnector: "local"
  connectors:
  - type: github
    id: github
    name: github
    config:
      clientID: "github-oauth-sample-id"
      clientSecretRef: "github-secretref"
